name: Unit Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          gradle-version: ${{ vars.GRADLE_VERSION }}

      - name: Run unit tests
        env:
          JWT_SECRET: ci-test-jwt-secret-key-of-32-bytes-min
          DATABASE_PASSWORD: postgres
        run: ./gradlew koverVerify

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/kover/html
